### PR TITLE
Texas tech

### PR DESCRIPTION
**Pull request by CuriousG102**
Don't merge yet. We don't have good data from Texas Tech. But a lot of new features in here. Support for overriding the hire date warning. Support for merge cells.

@rdmurphy 
@anniedaniel 
@brickaa

### CODE REVIEW

**Comment by CuriousG102** [comment]
On second thought, this carries new features, and we're not using the Tx Tech transformer anyway, so you could merge this for the features

**Comment by rdmurphy** [comment]
I'll going to wait to address this once until we finish this wave of updates. But good work! I would be curious in doing a test run of an entity that isn't Texas Tech just for sanity with these changes in place.

**Comment by CuriousG102** [comment]
@rdmurphy this is now done against the TX Tech data set. I would suggest merging in my other branch with the validation code and Becca's CY ISD branch first. Then I can pull them into this branch before you merge to prevent a lot of nasty merge conflicts(both in code and documentation) I've spotted.

**Comment by CuriousG102** [comment]
The documentation conflict is in reference to calculate_tenure and my changes to it. My changes render @brickaa's changes to ERRORS.md incorrect. In merging back master, I plan to change the text from:
+ERROR: ValueError: An employee was hired after the data was provided.
+Is DATE_PROVIDED correct?
+
+WHAT IT MEANS: Someone in your data has a hire date AFTER the date you obtained the data. First, check with the entity that this information is correct. If it is, and that person just hasn't started working yet, you'll need to include a function to ignore them.
+
+Add this function:
+```    
+    def calculate_tenure(self):
+        hire_date_data = map(int, self.hire_date.split('-'))
+        hire_date = date(hire_date_data[0], hire_date_data[1],
+                         hire_date_data[2])
+        tenure = float((self.DATE_PROVIDED - hire_date).days) / float(360)
+        if tenure < 0:
+            tenure = 0
+        return tenure
+```

to:
+ERROR: ValueError: An employee was hired after the data was provided.
+Is DATE_PROVIDED correct?
+
+WHAT IT MEANS: Someone in your data has a hire date AFTER the date you obtained the data. First, check with the entity that this information is correct. If it is, and that person just hasn't started working yet, set the class variable EMPLOYEES_HIRED_AFTER_SUBMISSION to True.

**Comment by CuriousG102** [comment]
On a side note, the fact that people can select as many races for themselves as they want gave TX Tech's race distribution the most hilariously long tail we'll probably ever have on Salary Explorer

**Comment by CuriousG102** [comment]
@rdmurphy master has been merged in.

**Pull request closed without merging**
