### PR TITLE
Beaumontisd

### PR DESCRIPTION
**Pull request by joliesky**
Ready for youuuu

### CODE REVIEW

**Comment by rdmurphy** [comment]
Holding until we check on the blank part-timers. Otherwise, the transformer is good to go.

**Comment by rdmurphy** [comment]
Are we still waiting on this update?

**Comment by joliesky** [comment]
I have now added part-timers and deleted those two people who were duplicates (confirmed with IT person)

**Comment by rdmurphy** [comment]
👍

**Pull request merged**
