### PR TITLE
Ut arlington

### PR DESCRIPTION
**Pull request by CuriousG102**
@rdmurphy

### CODE REVIEW

**Comment by CuriousG102** [comment]
Merge conflict looks like something stupid with __init__.py

**Comment by rdmurphy** [comment]
This is now error-ing due to invalid records.

```
Traceback (most recent call last):
  File "salaries/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/ryan/.virtualenvs/salaries-dev/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/ryan/.virtualenvs/salaries-dev/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/ryan/.virtualenvs/salaries-dev/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/ryan/.virtualenvs/salaries-dev/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Users/ryan/src/trib/tx_salaries/tx_salaries/management/commands/import_salary_data.py", line 62, in handle
    filename = self.fetch_file(**kwargs)
  File "/Users/ryan/src/trib/tx_salaries/tx_salaries/management/commands/import_salary_data.py", line 56, in fetch_file
    self.import_file(filename, **kwargs)
  File "/Users/ryan/src/trib/tx_salaries/tx_salaries/management/commands/import_salary_data.py", line 69, in import_file
    kwargs['label_row'])
  File "/Users/ryan/src/trib/tx_salaries/tx_salaries/utils/transformer.py", line 56, in transform
    data = transformer(labels, reader)
  File "/Users/ryan/src/trib/tx_salaries/tx_salaries/utils/transformers/base.py", line 178, in transform
    return transform_func(labels, source, record_class=record_class)
  File "/Users/ryan/src/trib/tx_salaries/tx_salaries/utils/transformers/base.py", line 127, in generic_transform
    "{0}".format(['\n'.join(warnings)]))
ValueError: Aborting the transformation because invalid records exist,and there is no override to accept invalid records.["WARNING: RECORD INVALID; {u'NAME FIRST': u'Amanda ', u'NAME MIDDLE': u' ', u'GENDER': u'FEMALE ', u'DEPARTMENT TITLE': u'CAREER SERVICES ', u'JOB TITLE': u'Customer Service Representative ', u'NAME SUFFIX': u' ', u'NAME LAST': u'Ashmead ', u'CONTINUOUS EMPLOYMENT DATE': u' ', u'FY ALLOCATIONS': u'18000', u'CAMPUS': u'THE UNIVERSITY OF TEXAS AT ARLINGTON', u'ETHNICITY': u' '}\nWARNING: RECORD INVALID; {u'NAME FIRST': u'Kaylee ', u'NAME MIDDLE': u'Paige ', u'GENDER': u'FEMALE ', u'DEPARTMENT TITLE': u'MATHEMATICS ', u'JOB TITLE': u'Support Specialist II ', u'NAME SUFFIX': u' ', u'NAME LAST': u'Woodward ', u'CONTINUOUS EMPLOYMENT DATE': u' ', u'FY ALLOCATIONS': u'15043', u'CAMPUS': u'THE UNIVERSITY OF TEXAS AT ARLINGTON', u'ETHNICITY': u' '}\nWARNING: RECORD INVALID; {u'NAME FIRST': u'Jennifer ', u'NAME MIDDLE': u'L ', u'GENDER': u'FEMALE ', u'DEPARTMENT TITLE': u'ADMISSIONS, RECORDS AND REGISTRATION ', u'JOB TITLE': u'Transcript Evaluator I ', u'NAME SUFFIX': u' ', u'NAME LAST': u'Davis ', u'CONTINUOUS EMPLOYMENT DATE': u' ', u'FY ALLOCATIONS': u'13344', u'CAMPUS': u'THE UNIVERSITY OF TEXAS AT ARLINGTON', u'ETHNICITY': u' '}\nWARNING: RECORD INVALID; {u'NAME FIRST': u'Richard ', u'NAME MIDDLE': u'J ', u'GENDER': u' ', u'DEPARTMENT TITLE': u'EARTH AND ENVIRONMENTAL SCIENCES ', u'JOB TITLE': u'Lecturer ', u'NAME SUFFIX': u'JR ', u'NAME LAST': u'Mcmullen ', u'CONTINUOUS EMPLOYMENT DATE': u' ', u'FY ALLOCATIONS': u'6500', u'CAMPUS': u'THE UNIVERSITY OF TEXAS AT ARLINGTON', u'ETHNICITY': u' '}\nWARNING: RECORD INVALID; {u'NAME FIRST': u'Julie ', u'NAME MIDDLE': u' ', u'GENDER': u' ', u'DEPARTMENT TITLE': u'LINGUISTICS - ENGLISH LANGUAGE INSTITUTE ', u'JOB TITLE': u'Specialist ', u'NAME SUFFIX': u' ', u'NAME LAST': u'Johnson ', u'CONTINUOUS EMPLOYMENT DATE': u' ', u'FY ALLOCATIONS': u'3331', u'CAMPUS': u'THE UNIVERSITY OF TEXAS AT ARLINGTON', u'ETHNICITY': u' '}"]
```

**Comment by CuriousG102** [comment]
Irony. Will fix tonight.

**Comment by CuriousG102** [comment]
So it looks like this is an actual problem with the data (these people don't have an attached hire date) that was going uncaught because is_valid was just throwing those things out. On the one hand I'm happy the exception I added has come in handy so soon. On the other hand I'm sad that I'm the first victim. I'm following up with UT Arlington.

**Comment by CuriousG102** [comment]
@rdmurphy solved

**Pull request closed without merging**
