### PR TITLE
City of houston

### PR DESCRIPTION
**Pull request by anniedaniel**

### CODE REVIEW

**Comment by rdmurphy** [comment]
This loaded, and looks good.

With race — what's the difference between `Other` and `Not given`? Did they give us the data with both of those categories, or did we create `Not given`?

**Comment by anniedaniel** [comment]
They have a category `Other` and we map blanks to `Not Given`

**Comment by rdmurphy** [comment]
Can we ask about the blanks? See if `Not given` is appropriate, or if they categorize the blanks differently. Thanks!

**Comment by anniedaniel** [comment]
>We contacted our Central Payroll and have been advised that those can be classified as “not given” – Code is missing in SAP.

**Pull request merged**
