### PR TITLE
Midwestern

### PR DESCRIPTION
**Pull request by joliesky**
Hooooray! Should be g2g

### CODE REVIEW

**Comment by rdmurphy** [comment]
These are the retirees, right?

```sh
WARNING: RECORD INVALID; {u'': u'', u'GROSS': u'50082.96', u'FULL_PART': u'O', u'TITLE': u'Assistant Professor', u'GENDER': u'F', u'MONTHS': u'11', u'DEPT': u'Academic Success Center', u'FNAME': u'Key,Susann F', u'HIREDATE': u'2003-01-03', u'ETHNICITY': u'White'}
WARNING: RECORD INVALID; {u'': u'', u'GROSS': u'98217.96', u'FULL_PART': u'O', u'TITLE': u'Chief Information Officer', u'GENDER': u'M', u'MONTHS': u'12', u'DEPT': u'Information Technology', u'FNAME': u'Kirkpatrick,Randy Craig', u'HIREDATE': u'1998-09-01', u'ETHNICITY': u'White'}
WARNING: RECORD INVALID; {u'': u'', u'GROSS': u'6265.63', u'FULL_PART': u'O', u'TITLE': u'Temp Staff Hourly', u'GENDER': u'F', u'MONTHS': u'12', u'DEPT': u'International Services', u'FNAME': u'Harwell,Rachel P', u'HIREDATE': u'2004-09-15', u'ETHNICITY': u'White'}
WARNING: RECORD INVALID; {u'': u'', u'GROSS': u'29913.95', u'FULL_PART': u'O', u'TITLE': u'Purchasing Assistant', u'GENDER': u'F', u'MONTHS': u'12', u'DEPT': u'Purchasing and Contract Mgmt Office', u'FNAME': u'Hodges, Vicky Lynn', u'HIREDATE': u'1999-12-01', u'ETHNICITY': u'White'}
WARNING: RECORD INVALID; {u'': u'', u'GROSS': u'84123.04', u'FULL_PART': u'O', u'TITLE': u'Professor', u'GENDER': u'M', u'MONTHS': u'9', u'DEPT': u'Social Work', u'FNAME': u'Fashimpar,Gary A', u'HIREDATE': u'1979-09-01', u'ETHNICITY': u'White'}
WARNING: RECORD INVALID; {u'': u'', u'GROSS': u'95067.04', u'FULL_PART': u'O', u'TITLE': u'Chief of Police', u'GENDER': u'M', u'MONTHS': u'12', u'DEPT': u'University Police', u'FNAME': u'Williams,Jay Dan', u'HIREDATE': u'2010-07-01', u'ETHNICITY': u'White'}
WARNING: RECORD INVALID; {u'': u'', u'GROSS': u'47822.96', u'FULL_PART': u'O', u'TITLE': u'Police Sergeant', u'GENDER': u'M', u'MONTHS': u'12', u'DEPT': u'University Police', u'FNAME': u'Cross,Joe M', u'HIREDATE': u'2002-01-14', u'ETHNICITY': u'White'}
```

**Comment by rdmurphy** [comment]
@joliesky ^

**Comment by rdmurphy** [comment]
Otherwise, it's 👍

**Comment by joliesky** [comment]
Yes, those people are gonesies

On Fri, Jun 3, 2016 at 1:13 PM, Ryan Murphy <notifications@github.com>
wrote:

> Otherwise, it's 👍
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/texastribune/tx_salaries/pull/121#issuecomment-223652818>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEb7OGUM7j-xJjmQxQGIJoIq9X_qrdtJks5qIG7ZgaJpZM4IeVlr>
> .
>



-- 



Jolie McCullough

Reporter, News Developer


823 Congress Ave., Ste. 1400

Austin, TX 78701

www.texastribune.org

<http://texastribune.org/>

M (505) 975-4620  D (512) 716-8612
@jsmccullou <http://twitter.com/jsmccullou>

**Pull request merged**
