### PR TITLE
Ut sanantonio

### PR DESCRIPTION
**Pull request by joliesky**
UT San Antonio is ready for testing and deployment!!!

### CODE REVIEW

**Comment by rdmurphy** [comment]
Why is UT Southwestern's transformer included in this?

**Comment by rdmurphy** [comment]
In the race category we have `Not given` and `Not specified` — do we get those directly from the agency? Are they the same?

**Comment by joliesky** [comment]
They are not the same. One was when they selected the "not specify" option. The other was when they did nothing. I suppose I could combine to say "not specified or given". As far as ut-southwestern, It's because I suck at github. Sorry :(

-- Jolie

**Comment by rdmurphy** [comment]
I think it's fine they both exist — just wanted to make sure they both came from the agency! Still not 100% sure what's going on with Southwestern. Is that new one?

**Comment by joliesky** [comment]
Yes. Southwestern is another one I'm working on right now. I must have started playing with it and didn't switch out of the branch. 

-- Jolie

**Comment by rdmurphy** [comment]
Kay. Can you `git rm` it from this branch tomorrow?

**Comment by joliesky** [comment]
Yeah

-- Jolie

**Comment by joliesky** [comment]
I removed the ut_southwestern.py file from this branch. Should be ready for production

**Pull request merged**
